package cshort012.gmail.com.newsapplication;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.annotation.Generated;

/**
 * Created by Short on 5/26/2015.
 * Autogenerated with http://www.jsonschema2pojo.org/
 */

@Generated("org.jsonschema2pojo")
public class StoryList {

    private String status;
    private String copyright;
    private String lastUpdated;
    private int numResults;
    private List<Story> stories = new ArrayList<Story>();
    private Map<String, Object> additionalProperties = new HashMap<String, Object>();

    /**
     *
     * @return
     *     The status
     */
    public String getStatus() {
        return status;
    }

    /**
     *
     * @param status
     *     The status
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     *
     * @return
     *     The copyright
     */
    public String getCopyright() {
        return copyright;
    }

    /**
     *
     * @param copyright
     *     The copyright
     */
    public void setCopyright(String copyright) {
        this.copyright = copyright;
    }

    /**
     *
     * @return
     *     The lastUpdated
     */
    public String getLastUpdated() {
        return lastUpdated;
    }

    /**
     *
     * @param lastUpdated
     *     The last_updated
     */
    public void setLastUpdated(String lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    /**
     *
     * @return
     *     The numResults
     */
    public int getNumResults() {
        return numResults;
    }

    /**
     *
     * @param numResults
     *     The num_results
     */
    public void setNumResults(int numResults) {
        this.numResults = numResults;
    }

    /**
     *
     * @return
     *     The stories
     */
    public List<Story> getStories() {
        return stories;
    }

    /**
     *
     * @param stories
     *     The stories
     */
    public void setStories(List<Story> stories) {
        this.stories = stories;
    }

    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

}